using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotelBooking.Interfaces
{
    internal interface IHotelBookingService
    {
        /// <summary>
        /// Retrieves a list of all currently active users
        /// along with their detailed profile information.
        /// </summary>
        Task<List<(int Id, string User, string Email, string First, string Last)>> GetActiveUsersWithProfiles();
        /// <summary>
        /// Gets all rooms marked as available,
        /// including associated hotel names, room types, and primary images.
        /// </summary>
        Task<List<(string Hotel, string Room, string Type, string HotelImg, string RoomImg)>> GetAvailableRoomsWithImages();
        /// <summary>
        /// Fetches all users in the system and concatenates 
        /// their first and last names into a single display name.
        /// </summary>
        Task<List<(int Id, string User, string Name)>> GetAllUsersWithProfiles();
        /// <summary>
        /// Performs a left join between hotels and images 
        /// to list all hotels and their associated image URLs.
        /// </summary>
        Task<List<(string Hotel, string Img)>> GetHotelsWithImagesLeft();
        /// <summary>
        /// Retrieves all hotel images currently stored in 
        /// the system alongside the name of the hotel they belong to.
        /// </summary>
        Task<List<(string Img, string Hotel)>> GetHotelsWithImagesRight();
        /// <returns>
        /// Returns a comprehensive list of booking records,
        /// including the username, hotel name, and total price paid.
        /// </returns>
        Task<List<(int Id, string User, string Hotel, decimal Price)>> GetBookingDetails();
        /// <summary>
        /// Counts the total number of bookings made by each user in the system.
        /// </summary>
        Task<List<(string User, int Count)>> GetUserBookingCounts();
        /// <summary>
        /// Calculates the average customer review rating for each hotel.
        /// </summary>
        Task<List<(string Hotel, double Avg)>> GetHotelAverageRating();
        /// <summary>
        /// Calculates the total revenue generated by
        /// each hotel based on the sum of all its room bookings.
        /// </summary>
        Task<List<(string Hotel, decimal Income)>> GetHotelTotalIncome();
        /// <summary>
        /// Groups bookings by user to find the earliest 
        /// check-in and latest check-out dates for each individual.
        /// </summary>
        Task<List<(int UserId, DateOnly First, DateOnly Last)>> GetUserBookingDates();
        /// <summary>
        /// Provides the minimum and maximum base price range 
        /// for each specific category of room type.
        /// </summary>
        Task<List<(string Type, decimal Min, decimal Max)>> GetRoomTypePriceRange();
        /// <summary>
        /// Groups hotels by city and returns the rating range 
        /// (min/max) for hotels with a rating of 3 or higher.
        /// </summary>
        Task<List<(string City, decimal Min, decimal Max)>> GetCityRatingRange();
        /// <summary>
        /// Retrieves rooms located in Tbilisi, ordered from lowest to highest price.
        /// </summary>
        Task<List<(string Room, decimal Price, string Hotel)>> GetRoomsInTbilisiByPrice();
    }
}
